WIDTH = 51
HEIGHT = 30

BALL_MAX_X_SPEED = 3

POWERUP_PROBABILITY = 1
POWERUP_ACTIVE_TIME = 20

MAX_PADDLE_SIZE = 17
MIN_PADDLE_SIZE = 3

ball_move_interval = 0.1
powerup_move_interval = 0.2

BRICK_FALL_DEADLINE = 60
RAINBOW_BLINK_INTERVAL = 0.25

LASER_MOVE_INTERVAL = 0.1
SHOOTING_INTERVAL = 1